### ISSUE TITLE
usersModule not recognized

### ISSUE THREAD

**Issue by naranjito72** [backEndLaVioleta/DanRobProject#1]
*usersModule*, although in app.module.ts, couldn't be recognized by the app.module when rendering the app. 
 ___(this issue happened at 18:00)___
 
Solution : 
>   entities: ['./**/entities/*.js'],

**Comment by danmarz** [comment]
Issue #1:

@naranjito72 This was fixed in [Users CRUD & DTOs done. 🚀](https://github.com/backEndLaVioleta/DanRobProject/commit/ea8c5fb7bc6e538d32b3a7af5bcf366d4da7f2f3) 🎯
